-- Table: public.posts

-- DROP TABLE IF EXISTS public.posts;

CREATE TABLE IF NOT EXISTS public.posts
(
    "postId" integer NOT NULL generated by default AS identity,
    title character varying(50) COLLATE pg_catalog."default",
    description character varying(500) COLLATE pg_catalog."default",
    "dateCreate" date,
    likes integer,
    tags text[] COLLATE pg_catalog."default",
    CONSTRAINT posts_pkey PRIMARY KEY ("postId")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.posts
    OWNER to postgres;

-- Table: public.post_tags

-- DROP TABLE IF EXISTS public.post_tags;

CREATE TABLE IF NOT EXISTS public.post_tags
(
    id integer NOT NULL generated by default AS identity,
    post_id integer,
    tag_id integer,
    CONSTRAINT post_tags_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.post_tags
    OWNER to postgres;

-- Table: public.tags

-- DROP TABLE IF EXISTS public.tags;

CREATE TABLE IF NOT EXISTS public.tags
(
    tag_id integer NOT NULL generated by default AS identity,
    tag_name character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT tags_pkey PRIMARY KEY (tag_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tags
    OWNER to postgres;

INSERT INTO posts (title, description, "dateCreate", likes, tags)
VALUES ('test', 'test', '2015-01-12', 0, ARRAY[]::text[])