version: '3'

services:
  api:
    container_name: api
    image: api
    restart: on-failure:3
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=db
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    restart: on-failure:3
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - ./db.sql:/docker-entrypoint-init.d/db.sql
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

volumes:
  pg_data: {}
