import { ThemeConfig } from "antd/es/config-provider/context";

const designTokens: ThemeConfig = {
  token: {
    colorPrimary: "#9e8e8e",
    colorSuccess: "#3eb25b",
    colorWarning: "#feba33",
    colorError: "#e5505d",
    colorInfo: "#337eff",
    colorTextBase: "#363a40",
    colorBgBase: "#ffffff",
    fontFamily: "Golos",
    fontSizeXL: 18,
    fontSizeHeading1: 48,
    fontSizeHeading2: 40,
    fontSizeHeading3: 32,
    fontSizeHeading4: 24,
    fontSizeHeading5: 18,
    borderRadius: 8,
    borderRadiusSM: 8,
    borderRadiusLG: 12,
    colorTextSecondary: "#616973",
    colorTextTertiary: "#989EA6",
    colorTextQuaternary: "#C2C6CC;",
    colorBgLayout: "#F0F3F7",
    controlHeight: 40,
  },
  components: {
    Button: {
      borderRadiusLG: 8,
      fontSizeLG: 14,
      colorBgContainer: "#DCDFE3",
      colorBorder: "transparent",
      controlHeightSM: 32,
      controlHeightLG: 48,
      controlHeight: 40,
      colorBgContainerDisabled: "#E1E6ED",
      colorTextDisabled: "#989EA6",
      controlOutlineWidth: 1,
      colorPrimaryBorder: "",
      colorPrimaryHover: "#2D6FE0",
    },
    Dropdown: {
      borderRadiusXS: 4,
      colorBgElevated: "#ffffff",
    },
    Menu: {
      radiusSubMenuItem: 8,
      colorItemBgSelected: "rgba(21, 28, 38, 0.05)",
      colorActiveBarWidth: 0,
      colorSubItemBg: "rgba(21, 28, 38, 0.05)",
      colorItemBg: "#ffffff",
      dropdownWidth: 280,
    },
    Pagination: {
      borderRadiusLG: 8,
      colorBgContainer: "#ffffff",
      colorPrimary: "#337eff",
      controlHeight: 40,
      controlHeightSM: 32,
      controlHeightLG: 48,
      colorBgTextHover: "rgba(51, 126, 255, 0.08)",
    },
    DatePicker: {
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontSizeLG: 14,
      controlPaddingHorizontal: 8,
      presetsMaxWidth: 160,
      borderRadiusLG: 8,
      marginXS: 8,
      paddingSM: 12,
      paddingXS: 8,
    },
    Input: {
      colorBorder: "#C1C6CC",
      borderRadiusLG: 8,
      colorBgContainerDisabled: "#E1E6ED",
      colorPrimaryHover: "#337eff",
      colorPrimaryActive: "#215ed9",
      colorPrimary: "#337eff",
      colorTextDescription: "#989EA6",
      colorTextPlaceholder: "#989EA6",
      colorTextDisabled: "#363A40",
    },
    InputNumber: {
      borderRadiusLG: 8,
      colorBgContainerDisabled: "#E1E6ED",
      colorBorder: "#C1C6CC",
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      controlPaddingHorizontal: 8,
      controlPaddingHorizontalSM: 4,
      fontSizeLG: 14,
      paddingSM: 12,
      colorTextPlaceholder: "#989EA6",
      colorTextDisabled: "#363A40",
    },
    Radio: {
      borderRadiusLG: 8,
      controlHeight: 40,
      controlHeightLG: 56,
      controlHeightSM: 32,
      fontSizeLG: 20,
      controlOutlineWidth: 8,
      lineWidth: 2,
    },
    Checkbox: {
      borderRadiusSM: 4,
    },
    Segmented: {
      borderRadiusLG: 8,
      lineWidth: 1,
      lineWidthBold: 0,
      controlHeight: 40,
      controlHeightLG: 48,
      controlHeightSM: 32,
      fontSizeLG: 14,
      colorBgElevated: "#337EFF",
      colorText: "#ffffff",
      colorFillSecondary: "#2D6FE0",
      colorBgLayout: "#F0F3F7",
      colorTextDisabled: "rgba(255, 255, 255, 1)",
      colorTextLabel: "rgba(54, 58, 64, 1)",
    },
    Tabs: {
      borderRadiusLG: 8,
    },
    Card: {
      boxShadowTertiary:
          "0 1px 2px 0 rgba(0, 0, 0, 0.03), 0 1px 6px -1px rgba(0, 0, 0, 0.02), 0 2px 4px 0 rgba(0, 0, 0, 0.02)",
      borderRadiusLG: 8,
      colorBgContainer: "#ffffff",
      colorBorderSecondary: "#ffffff",
      colorFillAlter: "rgba(255, 255, 255, 0.04)",
      colorPrimary: "#897c7c",
      colorText: "rgba(0, 0, 0, 1)",
      colorTextDescription: "rgba(0, 0, 0, 0.85)",
      fontSize: 14,
      colorTextDisabled: "#989EA6",
      colorTextHeading: "rgba(0, 0, 0, 1)",
    },
    Alert: {
      fontSizeIcon: 12,
    },
    Select: {
      controlHeightLG: 48,
      controlHeight: 40,
      controlHeightSM: 32,
      fontSizeLG: 14,
      fontSizeSM: 10,
      colorPrimaryHover: "#D1E3FC",
      controlOutline: "#337EFF",
      colorBgContainerDisabled: "#E1E6ED",
      colorTextDisabled: "#363A40",
      fontSizeIcon: 12,
    },
  },
};

export default designTokens;
